/**
 * Export the emails Supabase Auth sends as Go-template HTML.
 *
 *   npx tsx packages/emails/scripts/export-supabase.ts [--link=token-hash|confirmation-url] [--expires="15 minutes"]
 *
 * Writes, under supabase/templates/:
 *   <type>.html                       one per Supabase template or notification we use
 *   config.toml.snippet               [auth.email.template.*] and [auth.email.notification.*] blocks
 *   management-api.json               body for PATCH /v1/projects/{ref}/config/auth (hosted project)
 *
 * How: each template renders with no placeholder values, so the HTML keeps
 * literal `{signInUrl}` style tokens. Those are then swapped for Go template
 * variables (see src/templates/supabase.ts). Any token left over fails the run,
 * so an email never ships with a raw `{placeholder}` in it.
 *
 * Owned by D2 (templates lane) by assignment; lives in scripts/ beside D1's render script.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createElement } from 'react';
import { renderEmail } from '../src/components/render';
import { templatesById } from '../src/templates';
import {
  sharedVars,
  supabaseMappings,
  supabaseUnused,
  type LinkMode,
  type SupabaseMapping,
} from '../src/templates/supabase';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../..');
const outDir = join(repoRoot, 'supabase/templates');

function arg(name: string, fallback: string): string {
  const hit = process.argv.find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : fallback;
}

const mode = arg('link', 'token-hash') as LinkMode;
if (mode !== 'confirmation-url' && mode !== 'token-hash') throw new Error(`Unknown --link=${mode}`);
// Must match otp_expiry (L3: 900 s). Change both together.
const expiresIn = arg('expires', '15 minutes');
if (mode === 'confirmation-url') console.warn('WARNING: confirmation-url mode is for local testing only (see src/templates/supabase.ts).');

const escapeHtml = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const TOKEN = /\{([a-zA-Z][a-zA-Z0-9]*)\}/g;

function substitute(text: string, vars: Record<string, string>, html: boolean): string {
  return text.replace(TOKEN, (whole, key: string) => {
    const v = vars[key];
    if (v === undefined) return whole;
    // Go actions must stay raw; only the literal parts of a value (e.g. "&type=") need escaping.
    return html ? v.split(/(\{\{[^}]*\}\})/).map((part, i) => (i % 2 ? part : escapeHtml(part))).join('') : v;
  });
}

function leftovers(text: string): string[] {
  return [...new Set([...text.matchAll(TOKEN)].map((m) => m[0]))];
}

async function renderOne(id: string, m: SupabaseMapping): Promise<{ html: string; subject: string }> {
  const entry = templatesById[id];
  if (!entry) throw new Error(`No template for "${id}" (needed by Supabase ${m.type})`);
  const vars = { ...sharedVars(mode, m.otpType, expiresIn), ...m.vars };
  const raw = await renderEmail(createElement(entry.Component, { values: {} }));
  const html = substitute(raw, vars, true);
  const subject = substitute(entry.copy.subject, vars, false);
  const left = [...leftovers(html), ...leftovers(subject)];
  if (left.length) throw new Error(`${id} -> ${m.type}: no Supabase value for ${left.join(', ')}`);
  return { html, subject };
}

/** Join variants with Go conditionals: {{ if A }}x{{ else if B }}y{{ else }}default{{ end }}. */
function branch(parts: Array<{ when?: string; text: string }>): string {
  if (parts.length === 1) return parts[0]!.text;
  let out = '';
  parts.forEach((p, i) => {
    if (p.when) out += `{{ ${i === 0 ? 'if' : 'else if'} ${p.when} }}${p.text}`;
    else out += `{{ else }}${p.text}{{ end }}`;
  });
  return out;
}

const tomlString = (s: string) => JSON.stringify(s);

async function main() {
  mkdirSync(outDir, { recursive: true });
  const toml: string[] = [
    '# Generated by packages/emails/scripts/export-supabase.ts. Do not edit by hand.',
    `# Link mode: ${mode}. {expiresIn} rendered as "${expiresIn}"; keep it equal to otp_expiry.`,
    '',
  ];
  const api: Record<string, string | boolean> = {};

  for (const m of supabaseMappings) {
    const ids = [...(m.variants ?? []).map((v) => ({ when: v.when, id: v.id })), { when: undefined, id: m.id }];
    const rendered = await Promise.all(ids.map(async (v) => ({ when: v.when, ...(await renderOne(v.id, m)) })));
    const html = branch(rendered.map((r) => ({ when: r.when, text: r.html })));
    const subject = branch(rendered.map((r) => ({ when: r.when, text: r.subject })));

    const file = join(outDir, `${m.type}.html`);
    writeFileSync(file, html.endsWith('\n') ? html : `${html}\n`);
    const contentPath = `./${relative(repoRoot, file)}`;

    if (m.kind === 'template') {
      toml.push(`[auth.email.template.${m.type}]`, `subject = ${tomlString(subject)}`, `content_path = ${tomlString(contentPath)}`, '');
      api[`mailer_subjects_${m.type}`] = subject;
      api[`mailer_templates_${m.type}_content`] = html;
    } else {
      toml.push(`[auth.email.notification.${m.type}]`, 'enabled = true', `subject = ${tomlString(subject)}`, `content_path = ${tomlString(contentPath)}`, '');
      api[`mailer_notifications_${m.type}_enabled`] = true;
      api[`mailer_subjects_${m.type}_notification`] = subject;
      api[`mailer_templates_${m.type}_notification_content`] = html;
    }
    console.log(`${m.type.padEnd(18)} <- ${ids.map((v) => v.id).join(' | ')}  (${(html.length / 1024).toFixed(1)} KB)`);
  }

  for (const u of supabaseUnused.filter((u) => u.kind === 'notification')) {
    const on = Boolean(u.enabledWithDefault);
    toml.push(`# ${u.type}: ${u.why}${on ? ' Supabase default template.' : ''}`, `[auth.email.notification.${u.type}]`, `enabled = ${on}`, '');
    api[`mailer_notifications_${u.type}_enabled`] = on;
  }

  writeFileSync(join(outDir, 'config.toml.snippet'), toml.join('\n'));
  writeFileSync(join(outDir, 'management-api.json'), `${JSON.stringify(api, null, 2)}\n`);
  console.log(`Wrote ${supabaseMappings.length} templates to ${relative(repoRoot, outDir)}/`);
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
