// Writes docs/store/app-store.md from packages/content (the source of truth for every word).
//
//   npx tsx scripts/brand/store-listing.ts
//
// The content rules test fails if the document and packages/content drift apart.
import { writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { brand } from '../../packages/brand/index';
import { storeListing as s } from '../../packages/content/src/store.en';
import { en } from '../../packages/content/src/strings.en';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const n = (t: string) => `${t.length}`;

const SCREENS: Record<string, string> = {
  talk: 'Tonight: greeting, a prompt, Speak and Type',
  exact: 'Read it back: the letter with its two small fixes listed',
  voice: 'A letter from Mama with "Hear Mama"',
  book: "Asha's book, by month",
  together: 'Read together, dark mode',
  private: 'Settings: Privacy, Export your book, Delete account',
};

const md = `# App Store listing (v1.0)

Generated by \`scripts/brand/store-listing.ts\` from \`packages/content/src/store.en.ts\` and \`packages/brand\`. Edit the source, then run the script; the content rules test fails if this file drifts. Owner: brand and content. Updated 3 Oct 2026.

Rules this copy follows (docs/DECISIONS.md, 3 Oct 2026): no "beta" (D-060, guideline 2.2); no other platform's name (2.3.10); only what v1.0 does: seven spoken languages (D-056), co-parent only (D-055), no recording upload and no word highlight (D-059); privacy said once, calmly, in the promise's exact words (D-061); Lifestyle category and no health or development-tracking words (D-004, guideline 5.1.1(ix)).

## Fields

| Field | Value | Length / limit |
|---|---|---|
| Name | ${s.appName} | ${n(s.appName)} / 30 |
| Subtitle | ${s.subtitle} | ${n(s.subtitle)} / 30 |
| Promotional text | ${s.promotionalText} | ${n(s.promotionalText)} / 170 |
| Keywords | \`${s.keywords}\` | ${n(s.keywords)} / 100 |
| Primary category | ${s.primaryCategory} | |
| Support URL | ${s.supportUrl} | |
| Marketing URL | ${s.marketingUrl} | |
| Privacy Policy URL | ${s.privacyPolicyUrl} | |
| Support email | ${s.supportEmail} | |

Keywords repeat no word from the name or subtitle (Apple already indexes those), use no spaces, and name no competitor or other platform.

## Description (${n(s.description)} / 4000)

\`\`\`text
${s.description}
\`\`\`

## What's New (version 1.0)

\`\`\`text
${s.whatsNewV1}
\`\`\`

## Screenshots

Six frames, rendered from the web preview with the fictional family "Asha" and composed by \`scripts/brand/screenshots.mts\`. Sizes: 1320 x 2868 (6.9-inch) and 1242 x 2688 (6.5-inch), PNG, no alpha. Files: \`docs/store/screenshots/<size>/<nn>-<id>.png\`.

| # | Caption | Subline | Screen | Appearance |
|---|---|---|---|---|
${s.screenshots.map((f, i) => `| ${i + 1} | ${f.caption} | ${f.subline} | ${SCREENS[f.id] ?? ''} | ${f.scheme} |`).join('\n')}

The first three show in search results, so they carry the core promise: talk, kept exactly, your voice. Frame 5 is dark, as bedtime is (CREATIVE section 4). Frame 6 is the privacy promise, shown as the real controls rather than a badge.

## Privacy, said calmly

The promise appears once in the description, in the same words as the app (\`en.trust.promise\`):

> ${en.trust.promise}

Promotional text carries the short form. No locks, shields or "bank-level" language anywhere (VOICE.md, "How we talk about privacy").

## Before submission (founder and counsel)

- [ ] Counsel approves every privacy claim above (LEGAL-REQ-044 claims registry) and the Terms and Privacy Policy at ${brand.web.terms} and ${brand.web.privacy} are live.
- [ ] App Privacy answers in App Store Connect match \`docs/legal/app-store-privacy-labels.md\` and the shipped build.
- [ ] Subscriptions attached to the version with display names, and Family Sharing turned on for both products (D-053).
- [ ] Age rating questionnaire answered; category Lifestyle.
- [ ] App Review notes: a family memory journal; a due date is optional; no health service (D-004 5.1.1(ix) positioning); a demo account if review needs one.
- [ ] Every language named in the description is shipping in this build (D-056). If one slips, remove it here first.
- [ ] Screenshots regenerated from the release build's web preview and checked frame by frame.

## Benchmark notes (patterns, never assets)

- **Calm, Headspace:** one idea per frame, a short caption above the device, generous space, the palette doing the emotional work. We copy the rhythm, not their colours, type or art.
- **Day One:** privacy as a fact with a control behind it, not a fear. We show the Settings screen rather than a padlock.
- **Airbnb:** sentence-case captions, plain verbs, no superlatives. Our captions are six words or fewer where possible.
`;

writeFileSync(join(ROOT, 'docs', 'store', 'app-store.md'), md);
console.log('wrote docs/store/app-store.md');
