// Early Letters: all in-app copy (English).
// Placeholders: {name}, {child}, {signsAs}, {count}, {month}, {weekday}, {year}, {inviter}.
// Keys ending in "button", "cta" or "action" are button labels (22 characters or fewer).
// Keys ending in "link" are text links and may run longer.

export const en = {
  app: {
    name: "Early Letters",
    category: "memory book",
    tagline: "Exactly as you said it.",
    oneLine: "Early Letters, the memory book you fill by talking.",
  },

  common: {
    continueButton: "Continue",
    backButton: "Back",
    doneButton: "Done",
    saveButton: "Save",
    cancelButton: "Cancel",
    skipButton: "Skip for now",
    notNowButton: "Not now",
    tryAgainButton: "Try again",
    undoButton: "Undo",
    closeButton: "Close",
    editButton: "Edit",
    playButton: "Play",
    pauseButton: "Pause",
    signature: "From {signsAs}",
  },

  onboarding: {
    welcome: {
      title: "Early Letters",
      subtitle: "The memory book you fill by talking.",
      body: "A few words a day, in your own voice. Kept for {child} to read and hear for years.",
      startButton: "Begin the book",
      signInButton: "I already have a book",
      joinButton: "I was invited",
    },

    promise: {
      title: "Exactly as you said it.",
      body: "We tidy what the microphone got wrong. A stray \"um\", a misheard name, a missing comma.",
      body2: "We never rewrite, shorten or write for you. Every sentence is one you said.",
      recordingTitle: "Your voice stays too",
      recordingBody: "The recording is kept on this phone, so one day {child} can hear you say it.",
      privateNote: "Private by default. You choose what goes in the book.",
      cta: "That sounds right",
    },

    child: {
      title: "Who is this book for?",
      nameLabel: "Their name",
      namePlaceholder: "First name, or the name you use at home",
      nameHelp: "You can add a nickname later.",
      birthdayLabel: "Birthday",
      birthdayHelp: "We sort letters by {child}'s month of age.",
      expectingLabel: "Not here yet",
      expectingHelp: "Letters written before birth go into a chapter called Before You.",
      addAnotherButton: "Add another child",
      cta: "Continue",
    },

    signsAs: {
      title: "What does {child} call you?",
      body: "This is how your letters will be signed.",
      placeholder: "Papa, Mama, Amma, Baba, Dad",
      examplesLabel: "A few ideas",
      examples: ["Mama", "Papa", "Amma", "Appa", "Mummy", "Daddy", "Ma", "Baba"],
      notYetHelp: "Not talking yet? Pick the name you hope to hear.",
      preview: "From {signsAs}",
      cta: "Sign my letters",
    },

    dictionary: {
      title: "Your words, spelled your way",
      body: "Add names and home words you use often. We will spell them the way you do.",
      examples: "Like Nani, chhotu, or the name of a stuffed rabbit.",
      languagesBody: "Switch languages mid-sentence. Every word stays in the language you spoke it.",
      addPlaceholder: "Add a word or name",
      addButton: "Add word",
      emptyHint: "You can always add more from Settings.",
      cta: "Continue",
    },

    nameCheck: {
      title: "Say {child}'s name three times",
      body: "So we hear it the way you say it.",
      countLabel: "{count} of 3",
      listeningLabel: "Listening",
      heardLabel: "We heard:",
      correctPrompt: "Is that how you spell it?",
      yesButton: "Yes, that's it",
      fixButton: "Let me spell it",
      spellPlaceholder: "Type it your way",
      doneTitle: "Got it.",
      doneBody: "{child} will be spelled your way in every letter.",
      cta: "Continue",
    },

    reminder: {
      title: "When is your quiet moment?",
      body: "One gentle nudge a day, at a time that suits you. Most people choose after bedtime.",
      timeLabel: "Remind me at",
      noneOption: "No reminders",
      noneHelp: "You can write whenever you like.",
      permissionTitle: "One small reminder a day",
      permissionBody: "Just a nudge. You can change the time or turn it off any time.",
      cta: "Set reminder",
    },

    invite: {
      title: "Who else loves {child}?",
      body: "Grandparents, aunts, uncles. Their letters can go in the book too, when you say yes.",
      privacyNote: "They only see what you choose to share with them.",
      addButton: "Invite family",
      laterButton: "Maybe later",
    },

    finish: {
      title: "The book is open.",
      body: "Say one thing about {child} today. That is a letter.",
      cta: "Write the first one",
    },
  },

  tonight: {
    greeting: {
      earlyMorning: "Early start, {name}.",
      morning: "Good morning, {name}.",
      midday: "Hello, {name}.",
      afternoon: "Good afternoon, {name}.",
      evening: "Good evening, {name}.",
      night: "The house is quiet, {name}.",
      lateNight: "Still up, {name}. Take your time.",
    },
    subtitle: "What do you want {child} to know about today?",
    promptLabel: "A thought to start with",
    newPromptButton: "Another thought",
    writeFreelyButton: "Just talk",
    speakButton: "Speak",
    typeButton: "Type",
    notMuchButton: "Not much today",
    noteOrLetter: {
      label: "What is this?",
      note: "A note",
      noteHelp: "Something small, right now.",
      letter: "A letter",
      letterHelp: "Something you want {child} to keep.",
    },
    states: {
      ready: "Ready when you are.",
      readyHint: "Tap and talk. Pauses are fine.",
      listening: "Listening.",
      listeningHint: "Say it however it comes.",
      stillHere: "Still here. Take your time.",
      paused: "Paused.",
      resumeButton: "Keep talking",
      stopButton: "Finish",
      saving: "Keeping your words safe.",
      saved: "Saved, in your words.",
      savedLetter: "Signed and kept.",
      transcribing: "Writing down what you said.",
    },
    typing: {
      placeholder: "Write it the way you would say it.",
      letterPlaceholder: "Dear {child},",
      saveButton: "Save",
    },
    afterSave: {
      title: "Kept.",
      body: "One more page for {child}.",
      reviewButton: "Read it back",
      doneButton: "Done for tonight",
      anotherButton: "Add another",
    },
  },

  notMuch: {
    button: "Not much today",
    confirmTitle: "That counts.",
    confirmBody: "Some days are just days. We will keep a small line for today.",
    template: "{weekday}. Not much today. Just {child}, and us, and an ordinary day.",
    templateAlt: [
      "{weekday}. A quiet one. {child} was here, and so were we.",
      "{weekday}. Nothing big to tell. Just a day with {child} in it.",
      "{weekday}. Tired tonight. Loved {child} all day anyway.",
    ],
    addWordButton: "Add a few words",
    saveButton: "Keep this line",
    savedToast: "Kept. Rest well.",
  },

  review: {
    title: "Read it back",
    subtitle: "Here is what you said, lightly tidied.",
    trustLine: "We only fixed what got in the way of your words. Nothing added.",
    changesLabel: "{count} small fixes",
    noChanges: "Word for word. Nothing needed fixing.",
    showOriginalLink: "Show exactly what I said",
    showTidiedButton: "Show tidied version",
    originalLabel: "Exactly what you said",
    tidiedLabel: "Lightly tidied",
    undoEditButton: "Put it back",
    undoAllButton: "Keep it word for word",
    edits: {
      filler: {
        label: "Filler",
        explain: "We took out an \"um\" or \"uh\" so it reads smoothly.",
      },
      falseStart: {
        label: "False start",
        explain: "You started a sentence, then began again. We kept the second try.",
      },
      repeat: {
        label: "Repeat",
        explain: "A word came out twice in a row. We kept one.",
      },
      misheardName: {
        label: "Name",
        explain: "The microphone misheard a name. We used the spelling from your words list.",
      },
      punctuation: {
        label: "Punctuation",
        explain: "We added commas and full stops where you paused.",
      },
      grammarSlip: {
        label: "Small slip",
        explain: "A tiny slip of the tongue, like \"a apple\". We fixed only that.",
      },
      paragraph: {
        label: "Paragraph",
        explain: "You took a long pause, so we started a new paragraph.",
      },
    },
    lock: {
      button: "Keep this as said",
      explain: "Locked phrases stay exactly as you said them, slips and all.",
      lockedLabel: "Kept as said",
      unlockButton: "Allow small fixes",
    },
    voiceCheck: {
      question: "Does this sound like you?",
      yesButton: "Sounds like me",
      noButton: "Not quite",
      noFollowUp: "Tap any word to change it, or show exactly what you said.",
      thanks: "Thank you for telling us.",
    },
    destination: {
      title: "Where should this go?",
      addButton: "Add to {child}'s book",
      privateButton: "Keep private",
      privateHelp: "Private letters stay with you. You can add them to the book later.",
      addedToast: "Added to {child}'s book.",
      privateToast: "Kept just for you.",
    },
    addWordToDictionary: "Add \"{name}\" to your words",
    playButton: "Hear it",
  },

  quickNote: {
    title: "Quick note",
    subtitle: "Something small, right now.",
    placeholder: "What just happened?",
    speakButton: "Speak",
    typeButton: "Type",
    photoButton: "Add a photo",
    saveButton: "Save note",
    savedToast: "Noted. It is in Month {month}.",
    widgetLabel: "Quick note for {child}",
    lockScreenLabel: "Note for {child}",
  },

  book: {
    title: "{child}'s book",
    subtitle: "Early Letters: Year One",
    yearTitle: "Early Letters: Year {year}",
    beforeYouChapter: "Before You",
    chapterTitle: "Month {month}",
    chapterSubtitle: "{count} letters and notes",
    chapterSubtitleOne: "1 letter",
    chapterNewborn: "The first weeks",
    thisMonthLabel: "This month",
    signature: "From {signsAs}",
    together: "From {signsAs} and {child}",
    provenance: {
      spokenTidied: "Spoken, lightly tidied",
      spokenExact: "Spoken, word for word",
      typed: "Typed",
    },
    hearLink: "Hear it in {signsAs}'s voice",
    hearShort: "Hear {signsAs}",
    recordingOnPhone: "Recording kept on this phone",
    recordingBackedUp: "Recording kept and backed up",
    recordingElsewhere: "Recording kept on {signsAs}'s phone",
    privateLabel: "Private",
    familyLabel: "From family",
    filters: {
      all: "All",
      letters: "Letters",
      notes: "Notes",
      family: "Family",
      private: "Private",
    },
    empty: {
      bookTitle: "The first page is waiting.",
      bookBody: "Say one true thing about {child} today. That is how every book begins.",
      bookCta: "Write a letter",
      chapterTitle: "Month {month} is open.",
      chapterBody: "Whatever you add this month lands here.",
      familyTitle: "Family letters will gather here.",
      familyBody: "Invite a grandparent, aunt or uncle to add their words.",
      familyCta: "Invite family",
      privateTitle: "Nothing private yet.",
      privateBody: "Letters you keep for yourself will rest here.",
      searchTitle: "No letters with that word yet.",
    },
    entryMenu: {
      moveToBook: "Add to book",
      makePrivate: "Make private",
      editButton: "Edit words",
      showOriginal: "Show exactly what I said",
      shareButton: "Share",
      deleteButton: "Delete",
    },
    printPrompt: {
      title: "Early Letters: Year One",
      body: "{child}'s first year, in your words. Ready to hold in your hands.",
      cta: "See the printed book",
    },
  },

  readTogether: {
    title: "Read together",
    subtitle: "Open the book with {child}. Each letter plays in the voice that wrote it.",
    chooseMonth: "Pick a month",
    chooseAuthor: "Letters from",
    everyone: "Everyone",
    startButton: "Start reading",
    playButton: "Play",
    pauseButton: "Pause",
    nextButton: "Next letter",
    previousButton: "Back one",
    replayButton: "Hear it again",
    autoplayLabel: "Play the next one on its own",
    nowReading: "{signsAs}, Month {month}",
    noRecording: "This one was typed. Read it aloud together.",
    endOfMonth: "That was Month {month}. You are so loved.",
    endOfMonthAlt: "That was Month {month}. Every word was for you.",
    endOfBook: "That is every letter so far. More are still being written.",
    againButton: "Read it again",
    nextMonthButton: "On to Month {month}",
    finishButton: "Close the book",
    makeLetterTogether: {
      title: "Write one together",
      body: "Ask {child} a question and record the answer, together.",
      cta: "Write together",
    },
  },

  family: {
    title: "Family",
    subtitle: "The people who love {child}, adding their words.",
    invite: {
      title: "Invite someone to write",
      body: "They can send letters to {child}. You choose which ones go in the book.",
      nameLabel: "Their name",
      signsAsLabel: "What does {child} call them?",
      signsAsPlaceholder: "Nani, Dadi, Grandpa, Aunty",
      relationLabel: "Who are they to {child}?",
      sendButton: "Send invite",
      copyLinkButton: "Copy invite link",
      sentToast: "Invite sent to {signsAs}.",
      pendingLabel: "Invited",
      resendButton: "Send again",
      removeButton: "Remove",
    },
    shareMessage: {
      imessage: "Hi {signsAs}, it's {inviter}. I'm keeping a memory book of letters for {child}, and I'd love yours in it. Just talk, and your words and voice are kept for {child}. Tap here to join:",
      whatsapp: "{signsAs}, it's {inviter}. We are making a book of letters for {child}. Will you add yours? You just talk, in any language. Your voice is kept too. Join here:",
      short: "{inviter} would love your letters in {child}'s book.",
    },
    contributorWelcome: {
      title: "Welcome, {signsAs}.",
      body: "{inviter} is keeping a book of letters for {child}. Yours can be part of it.",
      howTitle: "How it works",
      howStep1: "Tap the microphone and talk, in any language.",
      howStep2: "We write down your words exactly as you said them.",
      howStep3: "{inviter} adds your letter to {child}'s book.",
      voiceNote: "Your voice is kept too, so {child} can hear you tell it.",
      privacyNote: "Only {inviter} sees your letters until they go in the book.",
      cta: "Write my first letter",
      firstPrompt: "Tell {child} about the first time you met.",
    },
    approval: {
      listTitle: "Letters from family",
      newBadge: "New",
      cardTitle: "A letter from {signsAs}",
      cardBody: "{signsAs} wrote to {child}. Would you like it in the book?",
      addButton: "Add to the book",
      keepAsideButton: "Keep it aside",
      keepAsideHelp: "It stays safe, just outside the book. {signsAs} will not be told.",
      thankButton: "Send a thank you",
      thankMessage: "Your letter is in {child}'s book. Thank you, {signsAs}.",
      addedToast: "{signsAs}'s letter is in the book.",
      settingLabel: "Add family letters on their own",
      settingHelp: "Skip the check and add every letter from {signsAs} straight to the book.",
    },
    contributorBook: {
      title: "Your letters to {child}",
      inBookLabel: "In the book",
      waitingLabel: "With {inviter}",
      emptyTitle: "Your first letter is waiting to be written.",
    },
  },

  notifications: {
    evening: [
      { title: "A minute for {child}?", body: "Tell {child} one thing about today. A sentence is plenty." },
      { title: "Tonight's letter", body: "What made you smile today? Say it out loud and we will keep it." },
      { title: "Dear {child},", body: "Your words, kept for {child}. Today, and long after." },
      { title: "The house is quiet", body: "A good moment for a few words to {child}." },
      { title: "One small thing", body: "What did {child} do today that you want to remember?" },
      { title: "Your voice, kept", body: "Talk for a minute. {child} will hear it one day, just as you said it." },
      { title: "Before you sleep", body: "Something {child} did, said or tried. Or just tap Not much today." },
      { title: "A page for {weekday}", body: "Whatever today held, it belongs in {child}'s book." },
    ],
    gentleReturn: {
      title: "{child}'s book is right here",
      body: "Whenever you like, there is a page for today. Just talk.",
    },
    familyLetter: {
      title: "A letter from {signsAs}",
      body: "{signsAs} wrote something for {child}. Have a read.",
    },
    familyAdded: {
      title: "Your letter is in the book",
      body: "{inviter} added your letter to {child}'s book. Thank you.",
    },
    monthOpen: {
      title: "Month {month} begins",
      body: "A new chapter in {child}'s book is open.",
    },
    birthday: {
      title: "Happy birthday, {child}",
      body: "A year of letters. Want to read them together today?",
    },
  },

  moments: {
    firstLetter: {
      title: "The first letter.",
      body: "Every book starts with one. This one is in your words.",
    },
    letters10: {
      title: "10 letters.",
      body: "Ten pieces of {child}'s story, told by you.",
    },
    letters50: {
      title: "50 letters.",
      body: "Fifty small moments, kept in your own voice.",
    },
    letters100: {
      title: "100 letters.",
      body: "A hundred times you stopped to tell {child} something. That is love, written down.",
    },
    letters365: {
      title: "365 letters.",
      body: "A year's worth of your words for {child}. All the work, all the love, kept.",
    },
    firstMonthComplete: {
      title: "Month {month} is a chapter now.",
      body: "{count} letters and notes, ready for {child} to read one day.",
      cta: "Read the chapter",
    },
    firstGrandparentLetter: {
      title: "{signsAs} wrote to {child}.",
      body: "The book has more than one voice now.",
    },
    firstReadTogether: {
      title: "You read it together.",
      body: "The first of many times {child} will hear these letters.",
    },
    monthSummary: "{count} letters this month",
    monthSummaryFamily: "{count} letters from family this month",
    dismissButton: "Lovely",
  },

  settings: {
    title: "Settings",
    sections: {
      book: "The book",
      voice: "Recordings",
      words: "Your words",
      family: "Family",
      reminders: "Reminders",
      data: "Your data",
    },
    signsAsLabel: "Sign my letters as",
    childLabel: "Child",
    birthdayLabel: "Birthday",
    dictionaryLabel: "Names and words",
    dictionaryHelp: "Spelled your way, every time.",
    tidyLabel: "Tidying",
    tidyOn: "Lightly tidied",
    tidyOff: "Word for word",
    tidyHelp: "Word for word keeps every um and false start. Either way, we never rewrite.",
    recordings: {
      title: "Recordings",
      keepLabel: "Keep recordings",
      keepHelp: "Your voice is saved with each letter, on this phone.",
      onPhoneTitle: "Kept on this phone",
      onPhoneBody: "Recordings live on this phone. Turn on backup to keep a copy if you change phones.",
      storageUsed: "{count} MB used on this phone",
    },
    backup: {
      title: "Encrypted backup",
      offLabel: "Backup is off",
      onLabel: "Backup is on",
      body: "Copies your letters and recordings to our servers, encrypted, so a new phone can bring them back.",
      honestNote: "Without backup, everything stays only on this phone.",
      turnOnButton: "Turn on backup",
      turnOffButton: "Turn off backup",
      lastBackup: "Last backed up {weekday}",
      backingUp: "Backing up",
    },
    export: {
      title: "Export",
      body: "Download every letter and recording, any time, free. Plain text and audio files.",
      button: "Export everything",
      preparing: "Gathering every letter. This can take a minute.",
      ready: "Your export is ready.",
    },
    delete: {
      entryTitle: "Delete this letter?",
      entryBody: "You can undo this for 30 days from Recently deleted.",
      entryConfirm: "Delete letter",
      entryToast: "Letter deleted.",
      recentlyDeleted: "Recently deleted",
      restoreButton: "Restore",
      bookTitle: "Delete the whole book?",
      bookBody: "Every letter and recording for {child} will be removed from this phone and from backup.",
      bookUndo: "You have 30 days to change your mind. After that, it cannot be restored.",
      bookExportFirst: "You can export everything first, free.",
      bookConfirm: "Delete the book",
      bookTypeToConfirmLabel: "Type {child}'s name to confirm",
      accountTitle: "Delete your account",
      accountConfirm: "Delete account",
    },
    reminders: {
      timeLabel: "Daily reminder",
      offLabel: "Off",
      help: "One gentle nudge, at the time you choose.",
    },
    privacyLine: "Private by default. You decide what goes in the book.",
    neverRewrite: "We never rewrite your words. We only tidy what the microphone got wrong.",
  },

  errors: {
    saveFailed: {
      title: "Not saved to the book yet",
      body: "Your words are safe on this phone. We will try again on our own.",
      button: "Try again now",
    },
    micDenied: {
      title: "We can't hear you yet",
      body: "Allow the microphone in Settings to speak your letters. Or type instead.",
      settingsButton: "Open Settings",
      typeButton: "Type instead",
    },
    transcriptionFailed: {
      title: "We could not write this one down",
      body: "The recording is safe on this phone. You can try again or type it.",
      button: "Try again",
    },
    offline: {
      title: "You're offline",
      body: "Keep talking. Everything is saved on this phone and will back up later.",
    },
    backupFailed: {
      title: "Backup paused",
      body: "Your letters are safe on this phone. We will back up when the connection returns.",
    },
    inviteExpired: {
      title: "This invite has expired",
      body: "Ask {inviter} to send a new one.",
    },
    storageLow: {
      title: "This phone is almost full",
      body: "New recordings may not fit. Turning on backup or freeing space will help.",
    },
    generic: {
      title: "Something went wrong",
      body: "Your words are safe. Please try again.",
    },
  },
} as const;

export type Strings = typeof en;
