/**
 * Renders a report as docs/insights/YYYY-MM-DD.md, and guards the result.
 * The guard is the last line: it refuses any output that contains something
 * shaped like an email, URL, UUID, token, phone number or a canary from the
 * fictional test family, so a bug upstream can never publish such a value.
 */
import { pct } from './engine';
import type { InsightsReport, Metric } from './types';

const fmtValue = (m: Metric, v: number | null) => (v === null ? 'n/a' : m.unit === 'rate' ? pct(v, 1) : m.unit === 'number' ? v.toFixed(2) : String(v));

export function renderReport(r: InsightsReport): string {
  const lines: string[] = [];
  lines.push(`# Insights ${r.date}`, '');
  if (r.synthetic) lines.push('> **Dry run on synthetic data.** Nothing here describes real families.', '');
  lines.push(
    'Generated by `scripts/insights/run.ts` (docs/analytics/INSIGHTS_LOOP.md). Counts and rates only: no letter text, names, ids or anything a person wrote. Server numbers cover every synced family, with cells under 10 suppressed; device numbers cover people who chose to share usage, and look better than reality (TRACKING_PLAN 1.4).',
    '',
    `Latest complete week: ${r.latestWeek ?? 'n/a'}. Sources: server aggregates ${r.sources.server ? 'yes' : 'no'}, device analytics ${r.sources.device ? 'yes' : 'no'}, language mix ${r.sources.languageMix ? 'yes' : 'not yet'}.`,
    '',
    '## Key numbers',
    '',
    '| Metric | Value | Previous | Week | Source |',
    '|---|---|---|---|---|',
  );
  for (const m of r.metrics) lines.push(`| ${m.label} | ${fmtValue(m, m.value)} | ${fmtValue(m, m.previous)} | ${m.week ?? 'n/a'} | ${m.source} |`);
  lines.push('', '## Findings', '');
  if (r.findings.length === 0) lines.push('- Nothing notable.');
  for (const f of r.findings) lines.push(`- (${f.area}, ${f.source}) ${f.text}`);
  lines.push('', '## Anomalies', '');
  if (r.anomalies.length === 0) lines.push('- None this week.');
  for (const a of r.anomalies) lines.push(`- ${a.label}, week of ${a.week}: ${a.value.toFixed(a.value < 1 ? 3 : 0)} against a recent average of ${a.baseline.toFixed(a.baseline < 1 ? 3 : 0)} (${a.direction} ${pct(Math.abs(a.change))}, ${a.source}).`);
  lines.push('', '## Backlog proposals (ranked)', '');
  if (r.proposals.length === 0) lines.push('No proposals this week.');
  r.proposals.forEach((p, i) => {
    lines.push(
      `### ${i + 1}. ${p.title}`,
      '',
      `- **Id:** \`${p.id}\` (stable across weeks; the weekly agent uses it to avoid duplicates)`,
      `- **Problem:** ${p.problem}`,
      `- **Evidence:** ${p.evidence.join('; ')}`,
      `- **Hypothesis:** ${p.hypothesis}`,
      `- **Change:** ${p.change}`,
      `- **Metric:** ${p.metric}`,
      `- **Confidence:** ${p.confidence} (score ${p.score})`,
      '',
    );
  });
  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}

/** Patterns that must never appear in a report. */
const FORBIDDEN: readonly [string, RegExp][] = [
  ['email', /[^\s@]+@[^\s@]+\.[^\s@]+/],
  ['url', /\bhttps?:\/\//i],
  ['uuid', /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i],
  ['jwt', /eyJ[A-Za-z0-9_-]{10,}/],
  ['token', /\b[A-Za-z0-9_-]{32,}\b/],
  ['phone', /\+\d[\d\s().-]{7,}/],
  ['canary', /\b(Asha|Nani)\b/],
];

export class ContentGuardError extends Error {
  constructor(public readonly kind: string) {
    super(`insights_content_guard:${kind}`);
  }
}

/** Throws (naming only the pattern kind, never the value) if the report holds anything forbidden. */
export function assertContentFree(markdown: string): void {
  for (const [kind, re] of FORBIDDEN) if (re.test(markdown)) throw new ContentGuardError(kind);
}
