/// <reference types="node" />
/**
 * Expo app config (TDD 01 3.10; BL-031, BL-M10). Replaces the scaffold
 * app.json (lumira-letters, Expo-blue splash, default microphone string).
 *
 * Identity comes from packages/brand only: name, scheme, bundle id, colours.
 * No public name is typed in this file (CLAUDE.md). The microphone purpose
 * string comes from src/lib/permission-copy.ts (part of pendingCopy; text
 * from docs/legal/app-store-privacy-labels.md 4, counsel review pending).
 *
 * Build profile (eas.json `env.EXPO_PUBLIC_APP_ENV`): development and
 * preview get a suffixed bundle id, so the real id is never used before
 * `brand.company.domain` is final (TDD 01 3.10 item 2, R-10). Do not run an
 * App Store Connect upload of the production profile until then.
 */
import type { ConfigContext, ExpoConfig } from 'expo/config';
import * as fs from 'node:fs';
import * as path from 'node:path';

type BrandModule = typeof import('../../packages/brand/index');
type PermissionCopyModule = typeof import('./src/lib/permission-copy');

const ROOT = typeof __dirname === 'string' ? __dirname : process.cwd();

/**
 * Loads a dependency-free TypeScript file at config time. Expo transpiles
 * only this file; nested .ts imports would need Node type stripping, which
 * EAS build images do not promise.
 */
function loadTs<T>(relative: string, req: (id: string) => unknown = require): T {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const ts = require('typescript') as typeof import('typescript');
  const file = path.join(ROOT, relative);
  const { outputText } = ts.transpileModule(fs.readFileSync(file, 'utf8'), {
    fileName: file,
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 },
  });
  const mod = { exports: {} as Record<string, unknown> };
  new Function('module', 'exports', 'require', outputText)(mod, mod.exports, req);
  return mod.exports as T;
}

const { brand, bundleId } = loadTs<BrandModule>('../../packages/brand/index.ts');
const { permissionCopy } = loadTs<PermissionCopyModule>('./src/lib/permission-copy.ts');

type AppEnv = 'development' | 'preview' | 'production';
const raw = process.env.EXPO_PUBLIC_APP_ENV;
const APP_ENV: AppEnv = raw === 'development' || raw === 'preview' ? raw : 'production';

const ID_SUFFIX: Record<AppEnv, string> = { development: '.dev', preview: '.preview', production: '' };
const appId = `${bundleId()}${ID_SUFFIX[APP_ENV]}`;
const microphone = permissionCopy.microphone.replace('{app}', brand.name);

/** "123-abc.apps.googleusercontent.com" -> "com.googleusercontent.apps.123-abc" (Google's iOS URL scheme). */
function reversedGoogleClientId(clientId: string | undefined): string | null {
  const m = /^([A-Za-z0-9-]+)\.apps\.googleusercontent\.com$/.exec((clientId ?? '').trim());
  return m ? `com.googleusercontent.apps.${m[1]}` : null;
}
const googleIosUrlScheme = reversedGoogleClientId(process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID);

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: brand.name,
  slug: brand.codename,
  version: '1.0.0',
  orientation: 'portrait',
  // Brand icons are generated by scripts/brand/icons.mjs from scripts/brand/mark.mjs; never edit the PNGs by hand.
  icon: './assets/brand/icon.png',
  scheme: brand.scheme,
  userInterfaceStyle: 'automatic',
  backgroundColor: brand.colors.paper,
  ios: {
    bundleIdentifier: appId,
    // iOS 18+ appearances. Light is opaque (App Store master); dark keeps transparency so the
    // system draws its own backdrop; tinted is grayscale on black for the system tint.
    icon: {
      light: './assets/brand/icon.png',
      dark: './assets/brand/icon-dark.png',
      tinted: './assets/brand/icon-tinted.png',
    },
    supportsTablet: false,
    infoPlist: {
      CADisableMinimumFrameDurationOnPhone: true,
    },
    // Sign in with Apple entitlement (PRD A-REQ-016; expo-apple-authentication plugin below).
    usesAppleSignIn: true,
    // Universal links for email sign-in and invites (/auth/callback, /i/*); the website serves the AASA
    // file (docs/ops/AUTH_SETUP.md section 5). Domain from packages/brand, never typed here.
    associatedDomains: [`applinks:${brand.publisher.domain}`],
  },
  android: {
    package: appId,
    // Android ships later (D-059); the layers are ready. Background is a colour, not an image.
    adaptiveIcon: {
      backgroundColor: brand.colors.accent,
      foregroundImage: './assets/brand/android-foreground.png',
      monochromeImage: './assets/brand/android-monochrome.png',
    },
    predictiveBackGestureEnabled: false,
  },
  web: {
    output: 'single',
    favicon: './assets/images/favicon.png',
  },
  plugins: [
    'expo-router',
    [
      'expo-splash-screen',
      {
        // Paper and the envelope mark (A-REQ-001), from scripts/brand/icons.mjs.
        image: './assets/brand/splash.png',
        imageWidth: 120,
        resizeMode: 'contain',
        backgroundColor: brand.colors.paper,
        dark: { image: './assets/brand/splash-dark.png', backgroundColor: brand.colors.paperDark },
      },
    ],
    'expo-sqlite',
    '@react-native-community/datetimepicker',
    [
      'expo-audio',
      {
        microphonePermission: microphone,
        // LEGAL-REQ-011: never record in the background. The plugin turns
        // background playback on by default, which adds UIBackgroundModes
        // `audio` (and Android foreground services); both stay off.
        enableBackgroundPlayback: false,
        enableBackgroundRecording: false,
      },
    ],
    'expo-apple-authentication',
    // Brand fonts embedded at build time (no runtime load on launch). The list is
    // @scribe/design-tokens/fonts `fontFiles` (repo-root paths); its .ttf requires are
    // Metro assets, so they are stubbed here.
    [
      'expo-font',
      {
        fonts: loadTs<typeof import('../../packages/design-tokens/fonts/index')>('../../packages/design-tokens/fonts/index.ts', () => 0).fontFiles.map(
          (f) => path.join(ROOT, '../..', f),
        ),
      },
    ],
    // Google sign-in (PRD A-REQ-017): only when this build has the iOS client id, because the
    // plugin needs its reversed form as a URL scheme (docs/ops/AUTH_SETUP.md section 3).
    ...(googleIosUrlScheme ? [['@react-native-google-signin/google-signin', { iosUrlScheme: googleIosUrlScheme }] as [string, object]] : []),
  ],
  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },
  extra: {
    appEnv: APP_ENV,
  },
});
