/**
 * Published signed documents served by the `config` function.
 *
 * GENERATED by `node scripts/packs/publish.mjs` (ADR 0016). Do not edit by
 * hand: each value is the exact JSON text of a SignedDocument, signed offline
 * with the founder's key. `null` means nothing is published yet; the function
 * answers 404 and the app keeps its bundled defaults (fail closed).
 */
export const REMOTE_CONFIG: string | null = null;
export const PACK_MANIFEST: string | null = null;
