/**
 * Published signed content bundles served by the `content` function, by
 * locale.
 *
 * GENERATED by `node scripts/packs/publish.mjs` (ADR 0016). Do not edit by
 * hand: each value is the exact JSON text of a SignedDocument, signed offline
 * with the founder's key. An empty map means nothing is published yet; the
 * function answers 404 and the app shows its packaged copy.
 */
export const CONTENT_BUNDLES: Readonly<Record<string, string>> = {};
