/// <reference types="node" />
import { describe, expect, it } from 'vitest';
import { zipSync } from 'fflate';
import { bytesPerSource, decodeVlq, groupByOwner, ipaBreakdown, listZip, ownerOf, parseThinningReport, unusedDependencies, verdict } from './lib';

describe('source map attribution', () => {
  it('decodes Base64 VLQ', () => {
    expect(decodeVlq('AAAA')).toEqual([0, 0, 0, 0]);
    expect(decodeVlq('AACA')).toEqual([0, 0, 1, 0]);
    expect(decodeVlq('gBAAA')).toEqual([16, 0, 0, 0]);
    expect(decodeVlq('D')).toEqual([-1]);
  });

  it('assigns generated bytes to the source of each segment', () => {
    // Line 1: "aaaa" from source 0, "bb" from source 1. Line 2: "ccc" from source 1.
    const code = 'aaaabb\nccc';
    const map = { sources: ['node_modules/left/index.js', '../../packages/api/src/x.ts'], mappings: 'AAAA,ICAA;AAAA' };
    const per = bytesPerSource(code, map);
    expect(per.get('node_modules/left/index.js')).toBe(4);
    expect(per.get('../../packages/api/src/x.ts')).toBe(5);
    expect(per.get('(unmapped)')).toBe(1);
    expect(groupByOwner(per)).toEqual([
      { owner: '@scribe/api', bytes: 5 },
      { owner: 'left', bytes: 4 },
      { owner: '(unmapped)', bytes: 1 },
    ]);
  });

  it('names owners', () => {
    expect(ownerOf('../../node_modules/@noble/hashes/sha2.js')).toBe('@noble/hashes');
    expect(ownerOf('node_modules/expo-router/build/a.js')).toBe('expo-router');
    expect(ownerOf('node_modules/a/node_modules/b/x.js')).toBe('b');
    expect(ownerOf('/repo/apps/mobile/src/lib/packs/engine.ts')).toBe('app:src/lib');
    expect(ownerOf('../../packages/content/src/strings.en.ts')).toBe('@scribe/content');
  });

  it('lists dependencies with nothing in the bundle', () => {
    expect(unusedDependencies(['expo-router', 'expo-symbols', '@scribe/core'], new Set(['expo-router']))).toEqual(['expo-symbols']);
  });
});

describe('IPA and thinning report', () => {
  it('reads an IPA central directory and groups the parts', () => {
    const zip = zipSync(
      {
        'Payload/Scribe.app/Scribe': new Uint8Array(1000),
        'Payload/Scribe.app/main.jsbundle': new Uint8Array(500).fill(7),
        'Payload/Scribe.app/Frameworks/hermes.framework/hermes': new Uint8Array(800),
        'Payload/Scribe.app/Assets.car': new Uint8Array(300),
        'Payload/Scribe.app/assets/node_modules/x.png': new Uint8Array(50),
      },
      { level: 6 },
    );
    const entries = listZip(zip);
    expect(entries.map((e) => e.name)).toContain('Payload/Scribe.app/main.jsbundle');
    const parts = Object.fromEntries(ipaBreakdown(entries).map((p) => [p.part, p.uncompressed]));
    expect(parts).toMatchObject({ 'main executable': 1000, 'JS bundle': 500, 'Frameworks/hermes.framework': 800, 'Assets.car': 300, 'JS assets': 50 });
  });

  it("parses Apple's App Thinning Size Report", () => {
    const text = `App Thinning Size Report for All Variants of ExampleApp

Variant: ExampleApp.ipa
Supported variant descriptors: [device: iPhone11,4, os-version: 12.0]
App + On Demand Resources size: 6.7 MB compressed, 18.6 MB uncompressed
App size: 6.7 MB compressed, 18.6 MB uncompressed
On Demand Resources size: Zero KB compressed, Zero KB uncompressed

Variant: ExampleApp-2.ipa
App size: 31.2 MB compressed, 80 MB uncompressed
`;
    expect(parseThinningReport(text)).toEqual([
      { variant: 'ExampleApp.ipa', compressed: 6_700_000, uncompressed: 18_600_000 },
      { variant: 'ExampleApp-2.ipa', compressed: 31_200_000, uncompressed: 80_000_000 },
    ]);
  });
});

describe('[DECISION-15] budget', () => {
  it('passes or fails on the best measurement available', () => {
    const js = { jsBundleBytes: 9_500_000, jsAssetsBytes: 200_000 };
    expect(verdict({ ...js, thinningMaxCompressed: 31_000_000 })).toMatchObject({ source: 'thinning_report', pass: true });
    expect(verdict({ ...js, thinningMaxCompressed: 41_000_000 })).toMatchObject({ source: 'thinning_report', pass: false });
    expect(verdict({ ...js, ipaBytes: 45_000_000 })).toMatchObject({ source: 'ipa', pass: false });
    expect(verdict(js)).toMatchObject({ source: 'js_only', pass: true, downloadBytes: null });
    expect(verdict({ jsBundleBytes: 13_000_000, jsAssetsBytes: 0 }).pass).toBe(false);
  });
});
